spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
    admin-user:
      id: demo
      password: demo
    filter.create: All
logging:
  level.root: INFO
  #file.name: logs/camunda-bpm-run.log